---
title: "NOTALFREQ"
output: html_notebook
---

```{r}
library(ggplot2)
library(dplyr)
```


```{r}
strain.table <- read.table('/Users/patch/Documents/HBKU/Research/F-BOX/F-BOX.Figure/data/strain.txt',header = T) %>% tibble()

CB <- strain.table %>% filter(SPE=='CBR') %>% pull(STR)
CN <- strain.table %>% filter(SPE=='CNI') %>% pull(STR)

strain.table %>%
  mutate(STR = STR %>% factor(levels = c(CB,CN))) -> strain.table
```


```{r}
read.table('/Users/patch/Documents/HBKU/Research/F-BOX/F-BOX.Figure/data/SV/JU1421.1k.FREQ.bed',col.names = c('Chr','Start','End','Freq')) %>%
  tibble() -> JU1421.freq.data
read.table('/Users/patch/Documents/HBKU/Research/F-BOX/F-BOX.Figure/data/SV/AF16.1k.FREQ.bed',col.names = c('Chr','Start','End','Freq')) %>%
  tibble() -> AF16.freq.data
```

# supplementary figure
```{r}
JU1421.freq.data %>%
  filter(Freq>0) %>%
  ggplot(aes(xmin=Start/1000000, xmax=End/1000000,ymin=Freq - 0.5 ,ymax=Freq + 0.5)) +
  geom_rect() +
  scale_y_continuous(breaks = seq(1,9)) +
  facet_grid(~ Chr,scales = 'free') +
  theme_classic() +
  theme(
    panel.border = element_rect(colour = "black", fill=NA, linewidth=1),
    panel.grid = element_blank(),
    panel.background = element_rect(fill = "#fcead9") , 
    #axis.text.x=element_blank(),
    axis.text.y=element_text(face="bold", color="black",size=15),
    #axis.ticks.x=element_blank(),
    axis.line.x=element_blank(),
    axis.line.y=element_line(linewidth = .5, colour = "black"),
    strip.background =element_rect(fill="#F6B06D")) +
  xlab('Reference genome position(Mb)') + ylab('Frequency')
```

```{r}
ggsave('/Users/patch/Documents/HBKU/Research/F-BOX/SVG/Supplementary/7.Div_freq/CN.Div_freq.pdf',width = 10,height = 3)
```


# supplementary figure
```{r}
AF16.freq.data %>%
  filter(Freq>0) %>%
  ggplot(aes(xmin=Start/1000000, xmax=End/1000000,ymin=Freq - 0.5 ,ymax=Freq + 0.5)) +
  geom_rect() +
  scale_y_continuous(breaks = seq(1,9)) +
  facet_grid(~ Chr,scales = 'free') +
  theme_classic() +
  theme(
    panel.border = element_rect(colour = "black", fill=NA, linewidth=1),
    panel.grid = element_blank(),
    panel.background = element_rect(fill = "#e5eaf3") , 
    #axis.text.x=element_blank(),
    axis.text.y=element_text(face="bold", color="black",size=15),
    #axis.ticks.x=element_blank(),
    axis.line.x=element_blank(),
    axis.line.y=element_line(linewidth = .5, colour = "black"),
    strip.background =element_rect(fill="#9AAED2")) +
  xlab('Reference genome position(Mb)') + ylab('Frequency')

```

```{r}
ggsave('/Users/patch/Documents/HBKU/Research/F-BOX/SVG/Supplementary/7.Div_freq/CB.Div_freq.pdf',width = 10,height = 3)
```





```{r}
JU1421.freq.data %>%
  filter(Freq>0) %>%
  ggplot() +
  geom_histogram(aes(Freq),bins = 8) +
  scale_x_continuous(breaks = seq(1,8)) +
  coord_flip() +
  theme_classic() +
  theme(
    panel.border = element_rect(colour = "black", fill=NA, linewidth=1),
    panel.grid = element_blank(),
    panel.background = element_rect(fill = "#fcead9") , 
    #axis.text.x=element_blank(),
    axis.text.y=element_text(face="bold", color="black",size=15),
    #axis.ticks.x=element_blank(),
    axis.line.x=element_blank(),
    axis.line.y=element_line(linewidth = .5, colour = "black"),
    strip.background =element_rect(fill="#F6B06D"))
```

```{r}
ggsave('/Users/patch/Documents/HBKU/Research/F-BOX/SVG/Supplementary/7.Div_freq/CN.Div_freq.bar.pdf',width = 3,height = 3)
```



```{r}
AF16.freq.data %>%
  filter(Freq>0) %>%
  ggplot() +
  geom_histogram(aes(Freq),bins = 6,binwidth=1) +
  coord_flip() +
  scale_x_continuous(breaks = seq(1,6)) +
  theme_classic() +
  theme(
    panel.border = element_rect(colour = "black", fill=NA, linewidth=1),
    panel.grid = element_blank(),
    panel.background = element_rect(fill = "#e5eaf3") , 
    #axis.text.x=element_blank(),
    axis.text.y=element_text(face="bold", color="black",size=15),
    #axis.ticks.x=element_blank(),
    axis.line.x=element_blank(),
    axis.line.y=element_line(linewidth = .5, colour = "black"),
    strip.background =element_rect(fill="#9AAED2"))

```

```{r}
ggsave('/Users/patch/Documents/HBKU/Research/F-BOX/SVG/Supplementary/7.Div_freq/CB.Div_freq.bar.pdf',width = 3,height = 3)
```








